***** Running 'python3 grade.py a1_autograding_files/unseen-1.jpg a1_autograding_files/unseen-1_detected.txt' *****
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(grade.py:2202438): Gdk-CRITICAL **: 18:28:05.965: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
***** Running 'python3 grade.py a1_autograding_files/unseen-1.jpg a1_autograding_files/unseen-1_detected.txt' *****
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(grade.py:2922798): Gdk-CRITICAL **: 22:14:38.402: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
